---
# tasks file for debops.grafana
- name: Get ownCloud APT GPG key
  apt_key:
    url: 'https://packagecloud.io/gpg.key'
    id: '{{ grafana_apt_repo_key_fingerprint }}'
    state: present

# Grafana provides packages only for wheezy but it works on jessie too.
- name: Configure Grafana APT repository
  apt_repository:
    repo: 'deb {{ grafana_apt_repo_base }}/{{ grafana_release }}/debian/ wheezy main'
    state: present
    update_cache: True

- name: Ensure grafana packages are installed
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ grafana_base_packages }}'
  tags: [ 'role::grafana:base_install' ]

- name: Divert grafana.ini
  command: dpkg-divert --quiet --local --divert /etc/grafana/grafana.ini.dpkg-divert
           --rename /etc/grafana/grafana.ini
  args:
    creates: '/etc/grafana/grafana.ini.dpkg-divert'

- name: Install config file
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'grafana'
    mode: '0640'
  with_items:
    - 'etc/grafana/grafana.ini'
  notify: [ 'Restart Grafana' ]

# Package doesn't enable grafana-server
- name: Enable Grafana service
  service:
    name: 'grafana-server'
    enabled: True

